name: single_result_bloc
description: Bloc extension, that adds support of one-time events
version: 0.0.3
homepage: https://github.com/Ae-Mc/single_result_bloc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
